package com.mindful.android.utils

object MindfulQuotes {

    fun getRandomQuote(): Map.Entry<String, String> =
        quotes.entries.shuffled().random()


    private val quotes: Map<String, String> = mapOf(
        "Thich Nhat Hanh" to "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
        "Anne Lamott" to "Almost everything will work again if you unplug it for a few minutes, including you.",
        "Marcel Proust" to "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
        "Sydney J. Harris" to "The time to relax is when you don't have time for it.",
        "Debasish Mridha" to "The greatest gift you can give yourself is a little bit of your own attention.",
        "W.B. Yeats" to "The world is full of magic things, patiently waiting for our senses to grow sharper.",
        "Gretchen Rubin" to "The more you nurture a habit of presence, the more you'll find yourself feeling naturally rejuvenated.",
        "Jon Kabat-Zinn" to "The best way to capture moments is to pay attention. This is how we cultivate mindfulness.",
        "William James" to "The greatest weapon against stress is our ability to choose one thought over another.",
        "Rumi" to "The quieter you become, the more you can hear.",
        "Pico Iyer" to "In an age of distraction, nothing can feel more luxurious than paying attention.",
        "G.K. Chesterton" to "The world will never starve for want of wonders, but only for want of wonder.",
        "Abraham Lincoln" to "The best thing about the future is that it comes one day at a time.",
        "Leonardo da Vinci" to "Simplicity is the ultimate sophistication.",
        "Terri Guillemets" to "The more you nurture a life of peace, the more you become the face of peace.",
        "Buddha" to "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly.",
        "Eckhart Tolle" to "Realize deeply that the present moment is all you have. Make the NOW the primary focus of your life.",
        "William Powers" to "We need to build pauses into our lives, where we can, collectively and individually, think about who we are as people.",
        "Mitchell Kapor" to "Getting information off the Internet is like taking a drink from a fire hydrant.",
        "Sherry Turkle" to "Technology challenges us to assert our human values, which means that first of all, we have to figure out what they are.",
        "Cal Newport" to "Clarity about what matters provides clarity about what does not.",
        "Arianna Huffington" to "Disconnecting from our technology to reconnect with ourselves is absolutely essential for wisdom.",
        "Nicholas Carr" to "The net is designed to be an interruption system, a machine geared to dividing attention.",
        "Susan Sontag" to "Attention is vitality. It connects you with others. It makes you eager. Stay eager.",
        "Tim Ferriss" to "The information we consume online is the mental equivalent of fast food.",
        "Henry David Thoreau" to "I went to the woods because I wished to live deliberately, to front only the essential facts of life.",
        "Simon Sinek" to "There is a difference between being connected and being present.",
        "Deepak Chopra" to "In the midst of movement and chaos, keep stillness inside of you.",
        "Pema Chödrön" to "The present moment is the only time over which we have dominion.",
        "Sharon Salzberg" to "Mindfulness isn’t difficult, we just need to remember to do it.",
        "S.N. Goenka" to "Live in the present, forget the past. Do not speculate about the future, it has not come.",
        "Tara Brach" to "The invitation of mindfulness is to recognize that every moment is an opportunity to awaken.",
        "Ram Dass" to "The quieter you become, the more you can hear.",
        "Nikki Rowe" to "Solitude is where I place my chaos to rest and awaken my inner peace.",
        "Matshona Dhliwayo" to "Distractions will do you more damage than your enemies ever could.",
        "T.S. Eliot" to "Distracted from distraction by distraction.",
        "Rachel Sklar" to "We don’t have to be connected all the time. It’s about finding the balance.",
        "Joshua Becker" to "Simplify your life by simplifying your screens.",
        "Cal Newport" to "Your attention is your currency; spend it wisely.",
        "Jenna Kutcher" to "Offline is the new luxury.",
        "Thich Nhat Hanh" to "Unplug and unwrap the gift of the present moment.",
        "Laura Distin" to "Don’t compare your real life to someone else’s controlled online content.",
        "Tech Wellness" to "Today I choose Me. Not social media.",
        "Leonard Cohen" to "There is a crack in everything, that’s how the light gets in.",
        "Maya Angelou" to "It’s okay not to be okay.",
        "Sylvia Plath" to "I took a deep breath and listened to the old brag of my heart. I am, I am, I am.",
        "Lady Gaga" to "Depression doesn’t take away your talents—it just makes them harder to find.",
        "Mariska Hargitay" to "Healing takes time, and asking for help is a courageous step.",
        "Mahatma Gandhi" to "Happiness is when what you think, what you say, and what you do are in harmony.",
        "Glenn Close" to "What mental health needs is more sunlight, more candor, and more unashamed conversation.",
        "Arthur Ashe" to "Start where you are. Use what you have. Do what you can.",
        "Martin Luther King Jr." to "If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward.",
        "Barack Obama" to "Hope is that thing inside us that insists, despite all the evidence to the contrary, that something better awaits us if we have the courage to reach for it and to work for it and to fight for it.",
        "Julian Seifter" to "You are not your illness. You have an individual story to tell. You have a name, a history, a personality. Staying yourself is part of the battle.",
        "Noam Shpancer" to "Mental health… is not a destination, but a process. It’s about how you drive, not where you’re going.",
        "Dan Millman" to "You don’t have to control your thoughts. You just have to stop letting them control you.",
        "Joubert Botha" to "Sometimes the people around you won’t understand your journey. They don’t need to, it’s not for them.",
        "Lisa Olivera" to "Just because no one else can heal or do your inner work for you doesn’t mean you can, should, or need to do it alone.",
        "John Green" to "There is hope, even when your brain tells you there isn’t.",
        "Jonathan Harnisch" to "I keep moving ahead, as always, knowing deep down inside that I am a good person and that I am worthy of a good life.",
        "Amy March" to "I am not afraid of storms for I am learning how to sail my ship.",
        "Mel Robbins" to "Your mental health is everything — prioritize it. Make the time like your life depends on it, because it does.",
        "Sam J. Miller" to "We are not our trauma. We are not our brain chemistry. That’s part of who we are, but we’re so much more than that.",
        "Demi Lovato" to "It’s possible to live well, feel well, and also find happiness with bipolar disorder or any other mental illness [you’re] struggling with.",
        "Virginia Woolf" to "No need to hurry, no need to sparkle, no need to be anybody but oneself.",
        "Charles Dickens" to "I have been bent and broken, but — I hope — into a better shape.",
        "Matt Haig" to "Mental health problems don’t define who you are. They are something you experience. You walk in the rain and you feel the rain, but, importantly, you are not the rain.",
        "Abertoli" to "Take your time healing, as long as you want. Nobody else knows what you’ve been through. How could they know how long it will take to heal you?",
        "Linda Poindexter" to "One small crack does not mean that you are broken, it means that you were put to the test and you didn’t fall apart.",
        "Charles Bukowski" to "Sometimes you climb out of bed in the morning and you think, I’m not going to make it, but you laugh inside — remembering all the times you’ve felt that way.",
        "Kahlil Gibran" to "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.",
        "Lalah Delia" to "Self-care is how you take your power back.",
        "Russ Kyle" to "Let your story go. Allow yourself to be present with who you are right now.",
        "Emery Lord" to "My dark days made me strong. Or maybe I already was strong, and they made me prove it.",
        "Kody Keplinger" to "You can’t control everything. Sometimes you just need to relax and have faith that things will work out. Let go a little and just let life happen.",
        "Rick Warren" to "Your illness is not your identity. Your chemistry is not your character.",
        "Albus Dumbledore" to "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
        "Steven Aitchison" to "Emotional pain is not something that should be hidden away and never spoken about. There is truth in your pain, there is growth in your pain, but only if it’s first brought out into the open.",
        "Buddha" to "You, yourself, as much as anybody in the entire universe, deserve your love and affection.",
        "Shannon L. Alder" to "The true definition of mental illness is when the majority of your time is spent in the past or future, but rarely living in the present.",
        "Viktor E. Frankl" to "When we are no longer able to change a situation, we are challenged to change ourselves.",
        "Dalai Lama" to "Calm mind brings inner strength and self-confidence, so that's very important for good health.",
        "Robin Sharma" to "Don’t live the same year 75 times and call it a life.",
        "James Clear" to "You do not rise to the level of your goals. You fall to the level of your systems.",
        "Tony Robbins" to "It’s not what we do once in a while that shapes our lives. It’s what we do consistently.",
        "Angela Duckworth" to "Enthusiasm is common. Endurance is rare.",
        "Brian Tracy" to "Successful people are simply those with successful habits.",
        "Stephen Covey" to "The key is not to prioritize what’s on your schedule, but to schedule your priorities.",
        "Brene Brown" to "You either walk inside your story and own it or you stand outside your story and hustle for your worthiness.",
        "J.K. Rowling" to "Rock bottom became the solid foundation on which I rebuilt my life.",
        "Mark Manson" to "The desire for more positive experience is itself a negative experience. And, paradoxically, the acceptance of one’s negative experience is itself a positive experience.",
        "James Baldwin" to "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
        "Albert Einstein" to "A calm and modest life brings more happiness than the pursuit of success combined with constant restlessness.",
        "Naval Ravikant" to "A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.",
        "Seneca" to "We suffer more often in imagination than in reality.",
        "Marcus Aurelius" to "You have power over your mind – not outside events. Realize this, and you will find strength.",
        "Epictetus" to "It’s not what happens to you, but how you react to it that matters.",
        "Lao Tzu" to "Nature does not hurry, yet everything is accomplished.",
        "Confucius" to "It does not matter how slowly you go as long as you do not stop.",
        "C.S. Lewis" to "You can’t go back and change the beginning, but you can start where you are and change the ending.",
        "Charles Duhigg" to "Change might not be fast and it isn’t always easy. But with time and effort, almost any habit can be reshaped.",
        "Craig D. Lounsbrough" to "We think we have to do something to be grateful or something has to be done in order for us to be grateful, when gratitude is a state of being.",
        "Ralph Waldo Emerson" to "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
        "Ryan Holiday" to "Almost nothing material is needed for a happy life, for he who has understood existence.",
        "Elizabeth Gilbert" to "Embrace the glorious mess that you are.",
        "Steve Jobs" to "Your time is limited, so don’t waste it living someone else’s life.",
        "Tony Schwartz" to "Energy, not time, is the fundamental currency of high performance.",
        "Hal Elrod" to "How you wake up each day and your morning routine (or lack thereof) dramatically affects your levels of success in every single area of your life.",
        "Leo Babauta" to "The things that matter most should never be at the mercy of the things that matter least.",
        "Anne Frank" to "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
        "Wayne Dyer" to "Change the way you look at things and the things you look at change.",
        "John Wooden" to "Don’t let what you cannot do interfere with what you can do.",
        "B.J. Fogg" to "Tiny changes can lead to big results if done consistently.",
        "Marie Forleo" to "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
        "Jim Rohn" to "Discipline is the bridge between goals and accomplishment.",
        "Les Brown" to "You don’t have to be great to get started, but you have to get started to be great.",
        "Seth Godin" to "The cost of being wrong is less than the cost of doing nothing.",
        "Melody Beattie" to "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.",
        "Zig Ziglar" to "People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily.",
        "Tony Hsieh" to "Stop chasing the money and start chasing the passion.",
        "Richie Norton" to "Simplicity is the ultimate sophistication. Do less, better.",
        "Chris Bailey" to "Productivity isn't about doing more. It's about doing what matters.",
        "Gary Keller" to "What’s the ONE thing you can do such that by doing it everything else will be easier or unnecessary?",
        "David Allen" to "Your mind is for having ideas, not holding them.",
        "Daniel Kahneman" to "Nothing in life is as important as you think it is, while you are thinking about it.",
        "Alan Watts" to "Muddy water is best cleared by leaving it alone.",
        "Carl Jung" to "Who looks outside, dreams; who looks inside, awakes.",
        "Yuval Noah Harari" to "In a world deluged by irrelevant information, clarity is power."
    )
}