package com.mindful.android.utils

object NsfwKeywords {
    val keywords = setOf(
        // General adult content
        "porn",
        "porno",
        "pornography",
        "adult",
        "sex",
        "xxx",
        "18+",
        "nsfw",
        "explicit",
        "uncensored",
        "hardcore",
        "softcore",
        "amateur",
        "leaked",

        // Sexual content terms
        "sex",
        "sexual",
        "intercourse",
        "erotic",
        "orgasm",
        "masturbation",
        "fetish",
        "kink",
        "bdsm",
        "dominatrix",
        "submission",
        "roleplay",
        "anal",
        "oral sex",
        "blowjob",
        "handjob",
        "cumshot",
        "facial",
        "deepthroat",
        "creampie",
        "69",
        "threesome",
        "foursome",

        // Body parts and slang
        "nude",
        "nudes",
        "naked",
        "boobs",
        "tits",
        "breasts",
        "nipples",
        "pussy",
        "vagina",
        "dick",
        "cock",
        "penis",
        "balls",
        "testicles",
        "butt",
        "ass",
        "anus",
        "milf",
        "teen",
        "ebony",
        "latina",
        "lesbian",

        // Adult platforms
        "onlyfans",
        "xvideos",
        "xxx",
        "xhamster",
        "pornhub",
        "redtube",
        "youporn",
        "xnxx",

        // Related euphemisms or queries
        "camgirl",
        "camsex",
        "hookup",
        "escort",
        "naughty",
        "striptease",
        "strip",
        "webcam",
    )
}