/// Type of session used for differentiating focus sessions
enum SessionType {
  study,
  work,
  exercise,
  meditation,
  creativeWriting,
  reading,
  programming,
  chores,
  projectPlanning,
  artAndDesign,
  languageLearning,
  musicPractice,
  selfCare,
  brainstorming,
  skillDevelopment,
  research,
  networking,
  cooking,
  sportsTraining,
  restAndRelaxation,
  other,
}

/// Map of [SessionType] and their respective string labels or titles
const Map<SessionType, String> sessionTypeLabels = {
  SessionType.study: 'Study',
  SessionType.work: 'Work',
  SessionType.exercise: 'Exercise',
  SessionType.meditation: 'Meditation',
  SessionType.creativeWriting: 'Creative Writing',
  SessionType.reading: 'Reading',
  SessionType.programming: 'Programming',
  SessionType.chores: 'Chores',
  SessionType.projectPlanning: 'Project Planning',
  SessionType.artAndDesign: 'Art and Design',
  SessionType.languageLearning: 'Language Learning',
  SessionType.musicPractice: 'Music Practice',
  SessionType.selfCare: 'Self-Care',
  SessionType.brainstorming: 'Brainstorming',
  SessionType.skillDevelopment: 'Skill Development',
  SessionType.research: 'Research',
  SessionType.networking: 'Networking',
  SessionType.cooking: 'Cooking',
  SessionType.sportsTraining: 'Sports Training',
  SessionType.restAndRelaxation: 'Rest and Relaxation',
  SessionType.other: 'Other',
};
